name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install meson
        run: pip install meson
      - name: Install ninja
        run: sudo apt install ninja-build
      - name: Build (gcc)
        run: |
          CXX=g++-10 meson build
          cd build
          ninja
      - name: Run tests (gcc)
        run: |
          cd build
          ninja test
      - name: Build (clang)
        run: |
          CXX=clang++-12 meson clang
          cd clang
          ninja
      - name: Run tests (clang)
        run: |
          cd clang
          ninja test
